// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJENArFxdU2XiPdXExCcrEZQzDWXQOSI',
    appId: '1:271984837864:android:ba57f5226afcdc6092f55d',
    messagingSenderId: '271984837864',
    projectId: 'congobonmarche',
    storageBucket: 'congobonmarche.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIZdwe30iwBC1ZEtW6lLpD42PliDTvuzI',
    appId: '1:271984837864:ios:1f2453ad3fbfd7ee92f55d',
    messagingSenderId: '271984837864',
    projectId: 'congobonmarche',
    storageBucket: 'congobonmarche.appspot.com',
    androidClientId: '271984837864-njs959jh42m4blc8q9ea6gcifik6f4e0.apps.googleusercontent.com',
    iosClientId: '271984837864-geruo107erjvskjq2it2klvmeasm935q.apps.googleusercontent.com',
    iosBundleId: 'com.congobonmarcheapp',
  );
}
